name: Release

on:
  push:
    branches:
      - main

jobs:
  push-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: bonney:3000
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push release image
        run: |
          chmod +x ./push-release.sh
          ./push-release.sh "v${{ gitea.run_number }}"
          docker tag bonney:3000/mandax/you:"v${{ gitea.run_number }}" bonney:3000/mandax/you:latest
          docker push bonney:3000/mandax/you:latest
